# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

Book.create([
    { title: 'The Hunchback of Notre Dame', author: 'Victor Hugo', synopsis: 'Hugos grand medieval melodrama tells the story of the beautiful Esmeralda, a gypsy girl loved by three men: Archdeacon Frollo, his adoptive son Quasimodo, bell-ringer of Notre-Dame cathedral, and Captain Phoebus. Falsely accused of trying to murder Phoebus, who attempts to rape her, Esmeralda is sentenced to death and rescued from the gallows by Quasimodo who defends her to the last.', cover_image: 'https://images.penguinrandomhouse.com/cover/9780307957818'},
    { title: 'Fire Bringer', author: 'David Clement-Davies', synopsis: 'Young buck Rannoch was born on the night his father was murdered and into a herd of deer where hunger for power has gradually whittled away at all that is true and good. He knows he must escape to survive. Chased by stags, with their fearsome antlers sharpened for the kill, he begins a treacherous journey into the unknown, and ahead of him lies a shocking and formidable search for truth and goodwill in the shadow of the Great Mountain.
    One day he will have to return to his home and face his destiny among the deer to fulfill the prophecy that has persistently given them hope: that one day a fawn will be born with the mark of an oak leaf on his forehead and that fawns courage will lead all the deer to freedom.', cover_image: 'https://images-na.ssl-images-amazon.com/images/I/81Z-bdACQKL.jpg'},
    { title: 'Schindlers List', author: 'Tom ', synopsis: '', cover_image: ''},
    { title: 'Game of Thrones', author: 'George R. R. Martin', synopsis: 'Long ago, in a time forgotten, a preternatural event threw the seasons out of balance. In a land where summers can last decades and winters a lifetime, trouble is brewing. The cold is returning, and in the frozen wastes to the north of Winterfell, sinister and supernatural forces are massing beyond the kingdom’s protective Wall. At the center of the conflict lie the Starks of Winterfell, a family as harsh and unyielding as the land they were born to. Sweeping from a land of brutal cold to a distant summertime kingdom of epicurean plenty, here is a tale of lords and ladies, soldiers and sorcerers, assassins and bastards, who come together in a time of grim omens.
    Here an enigmatic band of warriors bear swords of no human metal; a tribe of fierce wildlings carry men off into madness; a cruel young dragon prince barters his sister to win back his throne; and a determined woman undertakes the most treacherous of journeys. Amid plots and counterplots, tragedy and betrayal, victory and terror, the fate of the Starks, their allies, and their enemies hangs perilously in the balance, as each endeavors to win that deadliest of conflicts: the game of thrones.', cover_image: 'https://timweed.files.wordpress.com/2018/09/13496.jpg'},
    { title: 'Leviathan Wakes', author: 'James S. A. Corey', synopsis: 'Humanity has colonized the solar system—Mars, the Moon, the Asteroid Belt and beyond—but the stars are still out of our reach.
    Jim Holden is XO of an ice miner making runs from the rings of Saturn to the mining stations of the Belt. When he and his crew stumble upon a derelict ship, the Scopuli, they find themselves in possession of a secret they never wanted. A secret that someone is willing to kill for—and kill on a scale unfathomable to Jim and his crew. War is brewing in the system unless he can find out who left the ship and why.
    Detective Miller is looking for a girl. One girl in a system of billions, but her parents have money and money talks. When the trail leads him to the Scopuli and rebel sympathizer Holden, he realizes that this girl may be the key to everything.
    Holden and Miller must thread the needle between the Earth government, the Outer Planet revolutionaries, and secretive corporations—and the odds are against them. But out in the Belt, the rules are different, and one small ship can change the fate of the universe.', cover_image: 'https://images-na.ssl-images-amazon.com/images/I/91npjUXXkzL.jpg'},
    { title: 'Les Miserables', author: 'Victor Hugo', synopsis: 'Centered on the character Jean Valjean, an ex-convict in 19th-century France. The story spans many years as it tells of Valjeans release from prison and reformation as an industrialist while being constantly pursued by the morally strict inspector Javert while struggling to provide for his adopted daughter, Cosette.', cover_image: 'https://images-na.ssl-images-amazon.com/images/I/81SGVhaL+dL.jpg'},
    { title: 'Pride and Prejudice', author: 'Jane Austen', synopsis: 'Elizabeth Bennet, the daughter of a country gentleman, and Fitzwilliam Darcy, a rich aristocratic landowner find themselves struggling in a turbulent relationship while dealing with family ties, betrayal, and disapproving onlookers. Together, they must overcome the titular sins of pride and prejudice in order to fall in love and marry.', cover_image: 'https://i.pinimg.com/474x/fc/b7/4d/fcb74dc207c6b472c3e76519a7210bee--classic-books-big-books.jpg'},
    { title: 'Jurassic Park', author: 'Michael Chrichton', synopsis: 'A cautionary tale about genetic engineering, it presents the collapse of an amusement park showcasing genetically re-created dinosaurs to illustrate the mathematical concept of chaos theory and its real world implications.', cover_image: 'https://images-na.ssl-images-amazon.com/images/I/81rBVCDfrgL.jpg'},
    { title: 'The Prince', author: 'Niccolo Machiavelli', synopsis: 'Machiavelli composed The Prince as a practical guide for ruling (though some scholars argue that the book was intended as a satire and essentially a guide on how not to rule). This goal is evident from the very beginning, the dedication of the book to Lorenzo de’ Medici, the ruler of Florence. The Prince is not particularly theoretical or abstract; its prose is simple and its logic straightforward. These traits underscore Machiavellis desire to provide practical, easily understandable advice.', cover_image: 'https://images-na.ssl-images-amazon.com/images/I/71de1OC-ZIL.jpg'},
])